version: 2

models:
  - name: stg_customers
    columns: 
      - name: customer_id
        tests:
          - unique
          - not_null
  - name: stg_orders
    columns: 
      - name: order_id
        tests:
          - unique
          - not_null
      - name: status
        tests:
          - accepted_values:
              values:
                - completed
                - shipped
                - returned
                - placed
                - return_pending
      - name: customer_id
        tests:
          - relationships:
              to: ref('stg_customers')
              field: customer_id

sources:
  - name: jaffle_shop
    database: test_dbt
    tables:
      - name: orders
        loaded_at_field: _ETL_LOADED_AT
        freshness:
          warn_after: { count: 12, period: hour}
          error_after: { count: 24, period: hour}
        columns:
          - name: id
            tests:
              - unique
              - not_null
      - name: customers
        columns:
          - name: id
            tests:
              - unique
              - not_null