version: 2

models:
  - name: stg_payment
    columns: 
      - name: id
        tests:
          - unique
          - not_null

sources:
  - name: stripe
    database: test_dbt
    tables:
      - name: payment
        loaded_at_field: CREATED
        freshness:
          warn_after: { count: 12, period: hour}
          error_after: { count: 24, period: hour}
        columns:
          - name: id
            tests:
              - unique
              - not_null